<table style="width:100%; background-color: #D9EDF7">
  <tr>
    <td style="border: 1px solid #CFCFCF">
      <b>Weather data: Main notebook</b>
      <ul>
        <li><a href="main.ipynb">Main Notebook</a></li>
        <li>Downloading Notebook</li>
        <li><a href="documentation.ipynb">Documentation</a></li>
      </ul>
      <br>This Notebook is part of the <a href="http://data.open-power-system-data.org/weather_data">Weather data Datapackage</a> of <a href="http://open-power-system-data.org">Open Power System Data</a>.
    </td>
  </tr>
</table>

# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Introductory-Notes" data-toc-modified-id="Introductory-Notes-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introductory Notes</a></div><div class="lev2 toc-item"><a href="#How-to-use-the-script:" data-toc-modified-id="How-to-use-the-script:-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>How to use the script:</a></div><div class="lev1 toc-item"><a href="#Script-Setup" data-toc-modified-id="Script-Setup-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Script Setup</a></div><div class="lev1 toc-item"><a href="#Download-raw-data" data-toc-modified-id="Download-raw-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Download raw data</a></div><div class="lev2 toc-item"><a href="#Input" data-toc-modified-id="Input-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Input</a></div><div class="lev3 toc-item"><a href="#Timeframe" data-toc-modified-id="Timeframe-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Timeframe</a></div><div class="lev3 toc-item"><a href="#Geography-coordinates" data-toc-modified-id="Geography-coordinates-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Geography coordinates</a></div><div class="lev2 toc-item"><a href="#Subsetting-data" data-toc-modified-id="Subsetting-data-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Subsetting data</a></div><div class="lev1 toc-item"><a href="#Downloading-data" data-toc-modified-id="Downloading-data-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Downloading data</a></div><div class="lev2 toc-item"><a href="#Get-wind-data" data-toc-modified-id="Get-wind-data-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Get wind data</a></div><div class="lev2 toc-item"><a href="#Get-roughness-data" data-toc-modified-id="Get-roughness-data-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Get roughness data</a></div><div class="lev2 toc-item"><a href="#Get-radiation-data" data-toc-modified-id="Get-radiation-data-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Get radiation data</a></div><div class="lev2 toc-item"><a href="#Get-temperature-data" data-toc-modified-id="Get-temperature-data-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Get temperature data</a></div><div class="lev2 toc-item"><a href="#Get-air-density-data" data-toc-modified-id="Get-air-density-data-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Get air density data</a></div><div class="lev2 toc-item"><a href="#Get-air-pressure-data" data-toc-modified-id="Get-air-pressure-data-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Get air pressure data</a></div><div class="lev2 toc-item"><a href="#Get-lat-and-lon-dimensions" data-toc-modified-id="Get-lat-and-lon-dimensions-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Get lat and lon dimensions</a></div><div class="lev2 toc-item"><a href="#Check-the-precision-of-the-downloaded-data" data-toc-modified-id="Check-the-precision-of-the-downloaded-data-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>Check the precision of the downloaded data</a></div><div class="lev1 toc-item"><a href="#Setting-up-the-DataFrame" data-toc-modified-id="Setting-up-the-DataFrame-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Setting up the DataFrame</a></div><div class="lev2 toc-item"><a href="#Converting-the-timeformat-to-ISO-8601" data-toc-modified-id="Converting-the-timeformat-to-ISO-8601-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Converting the timeformat to ISO 8601</a></div><div class="lev2 toc-item"><a href="#Converting-wind-vectors-to-wind-speed" data-toc-modified-id="Converting-wind-vectors-to-wind-speed-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Converting wind vectors to wind speed</a></div><div class="lev2 toc-item"><a href="#Setting-up-data-Frame-for-roughness,-radiation,-temperature-and-air-parameters" data-toc-modified-id="Setting-up-data-Frame-for-roughness,-radiation,-temperature-and-air-parameters-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Setting up data Frame for roughness, radiation, temperature and air parameters</a></div><div class="lev2 toc-item"><a href="#Combining-the-data-Frames" data-toc-modified-id="Combining-the-data-Frames-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Combining the data Frames</a></div><div class="lev1 toc-item"><a href="#Structure-the-dataframe,-add-and-remove-columns" data-toc-modified-id="Structure-the-dataframe,-add-and-remove-columns-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Structure the dataframe, add and remove columns</a></div><div class="lev2 toc-item"><a href="#Calculating-the-displacement-height" data-toc-modified-id="Calculating-the-displacement-height-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Calculating the displacement height</a></div><div class="lev2 toc-item"><a href="#Adding-needed-and-removing-not-needed-columns" data-toc-modified-id="Adding-needed-and-removing-not-needed-columns-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Adding needed and removing not needed columns</a></div><div class="lev2 toc-item"><a href="#Renaming-and-sorting-columns" data-toc-modified-id="Renaming-and-sorting-columns-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Renaming and sorting columns</a></div><div class="lev2 toc-item"><a href="#First-look-at-the-final-data-Frame" data-toc-modified-id="First-look-at-the-final-data-Frame-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>First look at the final data Frame</a></div><div class="lev3 toc-item"><a href="#structure-and-format" data-toc-modified-id="structure-and-format-6.4.1"><span class="toc-item-num">6.4.1&nbsp;&nbsp;</span>structure and format</a></div><div class="lev3 toc-item"><a href="#resulting-dataframe" data-toc-modified-id="resulting-dataframe-6.4.2"><span class="toc-item-num">6.4.2&nbsp;&nbsp;</span>resulting dataframe</a></div><div class="lev1 toc-item"><a href="#Saving-data" data-toc-modified-id="Saving-data-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Saving data</a></div><div class="lev2 toc-item"><a href="#Save-as-CSV" data-toc-modified-id="Save-as-CSV-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Save as CSV</a></div><div class="lev2 toc-item"><a href="#Save-as-SQLite" data-toc-modified-id="Save-as-SQLite-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Save as SQLite</a></div><div class="lev2 toc-item"><a href="#Create-metadata" data-toc-modified-id="Create-metadata-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Create metadata</a></div><div class="lev2 toc-item"><a href="#Generating-checksums" data-toc-modified-id="Generating-checksums-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Generating checksums</a></div>

---


# Introductory Notes

This script contains code that allows the download, subset and processing of [MERRA-2](http://gmao.gsfc.nasa.gov/reanalysis/MERRA-2/) datasets (provided by NASA Goddard Space Flight Center) and export them as CSV.

**Weather data differ significantly from the other data types used resp. provided by OPSD** in that the sheer size of the data packages greatly exceeds OPSD's capacity to host them in a similar way as feed-in timeseries, power plant data etc. While the other data packages also offer a complete one-klick download of the bundled data packages with all relevant data this is impossible for weather datasets like MERRA-2 due to their size (variety of variables, very long timespan, huge geographical coverage etc.). It would make no sense to mirror the data from the NASA servers.

Instead we choose to provide only a **documented methodological script**. The  method describes one way to automatically obtain the desired weather data from the MERRA-2 database and simplifies resp. unifies alternative manual data obtaining methods in a single script.

**More detailed background information** on weather data can be found in the <a href="main.ipynb">Main notebook</a> and the [OPSD Wiki](https://github.com/Open-Power-System-Data/common/wiki/Information-on-weather-data) on Github.

## How to use the script:

To download MERRA-2 data, you have to **register at NASA earth data portal:**
1. Register an account at [https://urs.earthdata.nasa.gov/](https://urs.earthdata.nasa.gov/)
2. Go to "My Applications" -> "Approve More Applications" and add _NASA GESDISC DATA ARCHIVE_ (scroll down list)
3. Input your username and password when requested by the script

_Hints:_
* _Be aware that by registering you are "consenting to complete monitoring with no expectation of privacy"..._
* _It seems that the routine sometimes has problems with usernames which include upper case letters - avoid them if you can._

---
# Script Setup

In [4]:
import pandas as pd
import xarray as xr
import numpy as np
import requests
import logging
import yaml
import json
import os
import hashlib
import sqlalchemy

from datetime import datetime
from calendar import monthrange
from opendap_download.multi_processing_download import DownloadManager
import math
from functools import partial
import re
import getpass
from datetime import datetime, timedelta
import dateutil.parser

# Set up a log
logging.basicConfig(level=logging.INFO)
log = logging.getLogger('notebook')

---
# Download raw data

## Input

This part defines the input parameters according to the user and creates an URL that can download the desired MERRA-2 data via the OPeNDAP interface (see <a href="documentation.ipynb">documentation notebook</a> for information on OPeNDAP).

### Timeframe

Definition of desired timespan the data is needed for. (only complete years)

In [5]:
# User input of timespan
download_year = 2014

# Create the start date 2016-01-01
download_start_date = str(download_year) + '-01-01'

### Geography coordinates

Definition of desired coordinates. The user has to input two corner coordinates 
of a rectangular area (Format WGS84, decimal system).
* Northeast coordinate: lat_1, lon_1
* Southwest coordinate: lat_2, lon_2

The area/coordinates will be converted from lat/lon to the MERRA-2 grid coordinates.
Since the resolution of the MERRA-2 grid is 0.5 x 0.625°, the given exact coordinates will 
matched as close as possible.

In [6]:
# User input of coordinates
# ------
# Example: Germany (lat/lon)
# Northeastern point: 55.05917°N, 15.04361°E
# Southwestern point: 47.27083°N, 5.86694°E

# It is important to make the southwestern coordinate lat_1 and lon_1 since
# the MERRA-2 portal requires it!
# Southwestern coordinate
# lat_1, lon_1 = 47.27083, 5.86694 Germany
# Northeastern coordinate 
# lat_2, lon_2 = 55.05917, 15.04361 Germany

# Southwestern coordinate
lat_1, lon_1 = 3.9049, 116.6090
# Northeastern coordinate
lat_2, lon_2 = 21.7830, 126.9596

def translate_lat_to_geos5_native(latitude):
    """
    The source for this formula is in the MERRA2 
    Variable Details - File specifications for GEOS pdf file.
    The Grid in the documentation has points from 1 to 361 and 1 to 576.
    The MERRA-2 Portal uses 0 to 360 and 0 to 575.
    latitude: float Needs +/- instead of N/S
    """
    return ((latitude + 90) / 0.5)

def translate_lon_to_geos5_native(longitude):
    """See function above"""
    return ((longitude + 180) / 0.625)

def find_closest_coordinate(calc_coord, coord_array):
    """
    Since the resolution of the grid is 0.5 x 0.625, the 'real world'
    coordinates will not be matched 100% correctly. This function matches 
    the coordinates as close as possible. 
    """
    # np.argmin() finds the smallest value in an array and returns its
    # index. np.abs() returns the absolute value of each item of an array.
    # To summarize, the function finds the difference closest to 0 and returns 
    # its index. 
    index = np.abs(coord_array-calc_coord).argmin()
    return coord_array[index]

# The arrays contain the coordinates of the grid used by the API.
# The values are from 0 to 360 and 0 to 575
lat_coords = np.arange(0, 361, dtype=int)
lon_coords = np.arange(0, 576, dtype=int)

# Translate the coordinates that define your area to grid coordinates.
lat_coord_1 = translate_lat_to_geos5_native(lat_1)
lon_coord_1 = translate_lon_to_geos5_native(lon_1)
lat_coord_2 = translate_lat_to_geos5_native(lat_2)
lon_coord_2 = translate_lon_to_geos5_native(lon_2)


# Find the closest coordinate in the grid.
lat_co_1_closest = find_closest_coordinate(lat_coord_1, lat_coords)
lon_co_1_closest = find_closest_coordinate(lon_coord_1, lon_coords)
lat_co_2_closest = find_closest_coordinate(lat_coord_2, lat_coords)
lon_co_2_closest = find_closest_coordinate(lon_coord_2, lon_coords)

# Check the precision of the grid coordinates. These coordinates are not lat/lon. 
# They are coordinates on the MERRA-2 grid. 
log.info('Calculated coordinates for point 1: ' + str((lat_coord_1, lon_coord_1)))
log.info('Closest coordinates for point 1: ' + str((lat_co_1_closest, lon_co_1_closest)))
log.info('Calculated coordinates for point 2: ' + str((lat_coord_2, lon_coord_2)))
log.info('Closest coordinates for point 2: ' + str((lat_co_2_closest, lon_co_2_closest)))

INFO:notebook:Calculated coordinates for point 1: (187.8098, 474.57439999999997)
INFO:notebook:Closest coordinates for point 1: (188, 475)
INFO:notebook:Calculated coordinates for point 2: (223.566, 491.13536000000005)
INFO:notebook:Closest coordinates for point 2: (224, 491)

## Subsetting data

Combining parameter choices above/translation according to OPenDAP guidelines into URL-appendix

In [7]:
def translate_year_to_file_number(year):
    """
    The file names consist of a number and a meta data string. 
    The number changes over the years. 1980 until 1991 it is 100, 
    1992 until 2000 it is 200, 2001 until 2010 it is  300 
    and from 2011 until now it is 400.
    """
    file_number = ''
    
    if year >= 1980 and year < 1992:
        file_number = '100'
    elif year >= 1992 and year < 2001:
        file_number = '200'
    elif year >= 2001 and year < 2011:
        file_number = '300'
    elif year >= 2011:
        file_number = '400'
    else:
        raise Exception('The specified year is out of range.')
    
    return file_number
    


def generate_url_params(parameter, time_para, lat_para, lon_para):
    """Creates a string containing all the parameters in query form"""
    parameter = map(lambda x: x + time_para, parameter)
    parameter = map(lambda x: x + lat_para, parameter)
    parameter = map(lambda x: x + lon_para, parameter)
    
    return ','.join(parameter)
    
    

def generate_download_links(download_years, base_url, dataset_name, url_params):
    """
    Generates the links for the download. 
    download_years: The years you want to download as array. 
    dataset_name: The name of the data set. For example tavg1_2d_slv_Nx
    """
    urls = []
    for y in download_years: 
    # build the file_number
        y_str = str(y)
        file_num = translate_year_to_file_number(download_year)
        for m in range(1,13):
            # build the month string: for the month 1 - 9 it starts with a leading 0. 
            # zfill solves that problem
            m_str = str(m).zfill(2)
            # monthrange returns the first weekday and the number of days in a 
            # month. Also works for leap years.
            _, nr_of_days = monthrange(y, m)
            for d in range(1,nr_of_days+1):
                d_str = str(d).zfill(2)
                # Create the file name string
                file_name = 'MERRA2_{num}.{name}.{y}{m}{d}.nc4'.format(
                    num=file_num, name=dataset_name, 
                    y=y_str, m=m_str, d=d_str)
                # Create the query
                query = '{base}{y}/{m}/{name}.nc4?{params}'.format(
                    base=base_url, y=y_str, m=m_str, 
                    name=file_name, params=url_params)
                urls.append(query)
    return urls

requested_params = ['U2M', 'U10M', 'U50M', 'V2M', 'V10M', 'V50M', 'DISPH']
requested_time = '[0:1:23]'
# Creates a string that looks like [start:1:end]. start and end are the lat or
# lon coordinates define your area.
requested_lat = '[{lat_1}:1:{lat_2}]'.format(
                lat_1=lat_co_1_closest, lat_2=lat_co_2_closest)
requested_lon = '[{lon_1}:1:{lon_2}]'.format(
                lon_1=lon_co_1_closest, lon_2=lon_co_2_closest)



parameter = generate_url_params(requested_params, requested_time,
                                requested_lat, requested_lon)

BASE_URL = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/'
generated_URL = generate_download_links([download_year], BASE_URL, 
                                        'tavg1_2d_slv_Nx', 
                                        parameter)
            
# See what a query to the MERRA-2 portal looks like.        
log.info(generated_URL[0])

INFO:notebook:https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2014/01/MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4.nc4?U2M[0:1:23][188:1:224][475:1:491],U10M[0:1:23][188:1:224][475:1:491],U50M[0:1:23][188:1:224][475:1:491],V2M[0:1:23][188:1:224][475:1:491],V10M[0:1:23][188:1:224][475:1:491],V50M[0:1:23][188:1:224][475:1:491],DISPH[0:1:23][188:1:224][475:1:491]

---
# Downloading data

This part subsequently downloads the subsetted raw data from the MERRA-2-datasets. 
The download process is outsourced from the notebook, because it is a standard and repetitive process. If you are interested in the the code, see the [opendap_download module](opendap_download/).

_Note: Each of the following steps to download the data will take a few minutes, depending on the size of geographical area and amount of data (the total download routine e.G. for Germany takes roughly 70 minutes)._

## Get wind data

Parameters from the dataset [tavg1_2d_slv_Nx (M2T1NXSLV)](http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/contents.html)

In [8]:
# Download data (one file per day and dataset) with links to local directory.
# Username and password for MERRA-2 (NASA earthdata portal)
username = input('Username: ')
password = getpass.getpass('Password:')

# The DownloadManager is able to download files. If you have a fast internet 
# connection, setting this to 2 is enough. If you have slow wifi, try setting
# it to 4 or 5. If you download too fast, the data portal might ban you for a 
# day. 
NUMBER_OF_CONNECTIONS = 5

# The DownloadManager class is defined in the opendap_download module. 
download_manager = DownloadManager()
download_manager.set_username_and_password(username, password)
download_manager.download_path = 'download_wind'
download_manager.download_urls = generated_URL

# If you want to see the download progress, check the download folder you 
# specified
%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 20+ min.

Username: birgit.schachler
Password:········
CPU times: user 21.1 s, sys: 3.36 s, total: 24.5 s
Wall time: 13min 53s

## Get roughness data

Parameters from the dataset [tavg1_2d_rad_Nx (M2T1NXRAD)](https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXRAD.5.12.4/contents.html)

In [9]:
# Roughness data is in a different data set. The parameter is called Z0M. 
roughness_para = generate_url_params(['Z0M'], requested_time, 
                                     requested_lat, requested_lon)
ROUGHNESS_BASE_URL = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/'
roughness_links = generate_download_links([download_year], ROUGHNESS_BASE_URL,
                                          'tavg1_2d_flx_Nx', roughness_para)

download_manager.download_path = 'download_roughness'
download_manager.download_urls = roughness_links

# If you want to see the download progress, check the download folder you 
# specified.
%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 12+ min.

CPU times: user 17.8 s, sys: 1.34 s, total: 19.1 s
Wall time: 8min 52s

## Get radiation data

Parameters from the dataset [tavg1_2d_flx_Nx (M2T1NXFLX)](http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/contents.html)

In [10]:
# Parameters SWGDN and SWTDN
radiation_para = generate_url_params(['SWGDN', 'SWTDN'], requested_time, 
                                     requested_lat, requested_lon)
RADIATION_BASE_URL = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXRAD.5.12.4/'
radiation_links = generate_download_links([download_year], RADIATION_BASE_URL, 
                                         'tavg1_2d_rad_Nx', radiation_para)

download_manager.download_path = 'download_radiation'
download_manager.download_urls = radiation_links

%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 8+ min.

CPU times: user 17.1 s, sys: 1.24 s, total: 18.4 s
Wall time: 6min 54s

## Get temperature data

Parameters from the dataset [tavg1_2d_slv_Nx (M2T1NXSLV)](http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/contents.html)

In [11]:
# Parameter T2M (i.e. the temperature 2 meters above displacement height)
temperature_para = generate_url_params(['T2M'], requested_time, 
                                     requested_lat, requested_lon)
TEMPERATURE_BASE_URL = 'http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/'
temperature_links = generate_download_links([download_year], TEMPERATURE_BASE_URL, 
                                         'tavg1_2d_slv_Nx', temperature_para)

download_manager.download_path = 'download_temperature'
download_manager.download_urls = temperature_links

%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 13+ min.

CPU times: user 22.8 s, sys: 1.63 s, total: 24.4 s
Wall time: 8min 57s

## Get air density data

Parameters from the dataset [tavg1_2d_flx_Nx (M2T1NXFLX)](http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/contents.html)

In [12]:
# Parameter RHOA
density_para = generate_url_params(['RHOA'], requested_time, 
                                     requested_lat, requested_lon)
DENSITY_BASE_URL = 'http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXFLX.5.12.4/'
density_links = generate_download_links([download_year], DENSITY_BASE_URL, 
                                         'tavg1_2d_flx_Nx', density_para)

download_manager.download_path = 'download_density'
download_manager.download_urls = density_links

%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 13+ min.

CPU times: user 22 s, sys: 1.7 s, total: 23.7 s
Wall time: 8min 26s

## Get air pressure data

Parameters from the dataset [tavg1_2d_slv_Nx (M2T1NXSLV)](http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/contents.html)

In [13]:
# Parameters PS
pressure_para = generate_url_params(['PS'], requested_time, 
                                     requested_lat, requested_lon)
PRESSURE_BASE_URL = 'http://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/'
pressure_links = generate_download_links([download_year], PRESSURE_BASE_URL, 
                                         'tavg1_2d_slv_Nx', pressure_para)

download_manager.download_path = 'download_pressure'
download_manager.download_urls = pressure_links

%time download_manager.start_download(NUMBER_OF_CONNECTIONS)

# Download time approx. 15+ min.

CPU times: user 21.6 s, sys: 1.54 s, total: 23.2 s
Wall time: 9min 31s

## Get lat and lon dimensions

For now, the dataset only has MERRA-2 grid coordinates. To translate the points
back to "real world" coordinates, the data portal offers a dimension scale file.

In [14]:
# The dimensions map the MERRA2 grid coordinates to lat/lon. The coordinates 
# to request are 0:360 wheare as the other coordinates are 1:361
requested_lat_dim = '[{lat_1}:1:{lat_2}]'.format(
                    lat_1=lat_co_1_closest, lat_2=lat_co_2_closest)
requested_lon_dim = '[{lon_1}:1:{lon_2}]'.format(
                    lon_1=lon_co_1_closest , lon_2=lon_co_2_closest )

lat_lon_dimension_para = 'lat' + requested_lat_dim + ',lon' + requested_lon_dim

# Creating the download url.
dimension_url = 'https://goldsmr4.sci.gsfc.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2014/01/MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4.nc4?'
dimension_url = dimension_url + lat_lon_dimension_para
download_manager.download_path = 'dimension_scale'
download_manager.download_urls = [dimension_url]

# Since the dimension is only one file, we only need one connection. 
%time download_manager.start_download(1)

CPU times: user 48 ms, sys: 4 ms, total: 52 ms
Wall time: 7.94 s

## Check the precision of the downloaded data

Due to the back and forth conversion from "real world" coordinates to MERRA-2 grid points,
this part helps you to check if the conversion was precise enough.

In [15]:
file_path = os.path.join('dimension_scale', DownloadManager.get_filename(
        dimension_url))

with xr.open_dataset(file_path) as ds_dim:
    df_dim = ds_dim.to_dataframe()

lat_array = ds_dim['lat'].data.tolist()
lon_array = ds_dim['lon'].data.tolist()

# The log output helps evaluating the precision of the received data.
log.info('Requested lat: ' + str((lat_1, lat_2)))
log.info('Received lat: ' + str(lat_array))
log.info('Requested lon: ' + str((lon_1, lon_2)))
log.info('Received lon: ' + str(lon_array))

INFO:notebook:Requested lat: (3.9049, 21.783)
INFO:notebook:Received lat: [4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5, 12.0, 12.5, 13.0, 13.5, 14.0, 14.5, 15.0, 15.5, 16.0, 16.5, 17.0, 17.5, 18.0, 18.5, 19.0, 19.5, 20.0, 20.5, 21.0, 21.5, 22.0]
INFO:notebook:Requested lon: (116.609, 126.9596)
INFO:notebook:Received lon: [116.875, 117.5, 118.125, 118.75, 119.375, 120.0, 120.625, 121.25, 121.875, 122.5, 123.125, 123.75, 124.375, 125.0, 125.625, 126.25, 126.875]

---
# Setting up the DataFrame

This part sets up a DataFrame and reads the raw data into it. First the wind data and adding the remaining data afterwards.

In [18]:
def extract_date(data_set):
    """
    Extracts the date from the filename before merging the datasets. 
    """
    try:
        # The attribute name changed during the development of this script
        # from HDF5_Global.Filename to Filename. 
        if 'HDF5_GLOBAL.Filename' in data_set.attrs:
            f_name = data_set.attrs['HDF5_GLOBAL.Filename']
        elif 'Filename' in data_set.attrs:
            f_name = data_set.attrs['Filename']
        else: 
            raise AttributeError('The attribute name has changed again!')
        
        # find a match between "." and ".nc4" that does not have "." .
        exp = r'(?<=\.)[^\.]*(?=\.nc4)'
        res = re.search(exp, f_name).group(0)
        # Extract the date. 
        y, m, d = res[0:4], res[4:6], res[6:8]
        date_str = ('%s-%s-%s' % (y, m, d))
        data_set = data_set.assign(date=date_str)
        return data_set

    except KeyError:
        # The last dataset is the one all the other sets will be merged into. 
        # Therefore, no date can be extracted.
        return data_set
        

file_path = os.path.join('download_wind', '*.nc4')

try:
    with xr.open_mfdataset(file_path, concat_dim='date',
                           preprocess=extract_date) as ds_wind:
        print(ds_wind)
        df_wind = ds_wind.to_dataframe()
        
except xr.MergeError as e:
    print(e)

<xarray.Dataset>
Dimensions:  (date: 365, lat: 37, lon: 17, time: 24)
Coordinates:
  * date     (date) <U10 '2014-01-01' '2014-01-02' '2014-01-03' '2014-01-04' ...
Dimensions without coordinates: lat, lon, time
Data variables:
    U2M      (date, time, lat, lon) float64 0.03831 0.257 -1.14 -1.895 ...
    V50M     (date, time, lat, lon) float64 -0.4134 -0.4634 -0.5174 0.4489 ...
    DISPH    (date, time, lat, lon) float64 21.94 10.75 3.19 6.549e-06 0.0 ...
    V2M      (date, time, lat, lon) float64 0.002162 -0.2036 -0.3902 0.4235 ...
    V10M     (date, time, lat, lon) float64 -0.1759 -0.3177 -0.4469 0.4487 ...
    U50M     (date, time, lat, lon) float64 0.3126 0.4442 -1.315 -2.112 ...
    U10M     (date, time, lat, lon) float64 0.2127 0.3978 -1.222 -2.008 ...
Attributes:
    History:                           Original file generated: Mon Dec  8 12...
    Comment:                           GMAO filename: d5124_m2_jan10.tavg1_2d...
    Filename:                          MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    Format:                            NetCDF-4/HDF-5
    SpatialCoverage:                   global
    VersionID:                         5.12.4
    TemporalRange:                     1980-01-01 -> 2016-12-31
    identifier_product_doi_authority:  http://dx.doi.org/
    ShortName:                         M2T1NXSLV
    GranuleID:                         MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    ProductionDateTime:                Original file generated: Mon Dec  8 12...
    LongName:                          MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    Title:                             MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    SouthernmostLatitude:              -90.0
    NorthernmostLatitude:              90.0
    WesternmostLongitude:              -180.0
    EasternmostLongitude:              179.375
    LatitudeResolution:                0.5
    LongitudeResolution:               0.625
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/VJAFPLI1CSIV
    RangeBeginningDate:                2014-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   2014-01-01
    RangeEndingTime:                   23:59:59.000000
    DODS_EXTRA.Unlimited_Dimension:    time
    history:                           2017-12-18 12:48:49 GMT Hyrax-1.13.4 h...

In [19]:
df_wind.reset_index(inplace=True)

In [20]:
start_date = datetime.strptime(download_start_date, '%Y-%m-%d')

def calculate_datetime(d_frame):
    """
    Calculates the accumulated hour based on the date.
    """
    cur_date = datetime.strptime(d_frame['date'], '%Y-%m-%d')
    hour = int(d_frame['time'])
    delta = abs(cur_date - start_date).days
    date_time_value = (delta * 24) + (hour)
    return date_time_value


df_wind['date_time_hours'] = df_wind.apply(calculate_datetime, axis=1)
df_wind

,date,lat,lon,time,U2M,V50M,DISPH,V2M,V10M,U50M,U10M,date_time_hours
0,2014-01-01,0,0,0,0.038314,-0.413376,21.937500,0.002162,-0.175894,0.312650,0.212723,0
1,2014-01-01,0,0,1,0.001318,-0.492615,21.937500,-0.002465,-0.176514,-0.509410,-0.191207,1
2,2014-01-01,0,0,2,-0.032648,-0.270592,21.937500,-0.000080,-0.061454,-1.062879,-0.500116,2
3,2014-01-01,0,0,3,-0.046789,-0.008683,21.937500,0.008438,0.074510,-1.284535,-0.624029,3
4,2014-01-01,0,0,4,-0.059219,0.166052,21.937500,0.012166,0.158131,-1.457027,-0.721930,4
5,2014-01-01,0,0,5,-0.074952,0.260315,21.937500,0.010508,0.187717,-1.690463,-0.830301,5
6,2014-01-01,0,0,6,-0.086912,0.456126,21.937500,0.015211,0.253542,-1.856832,-0.899296,6
7,2014-01-01,0,0,7,-0.084374,0.576638,21.937500,0.018128,0.292173,-1.829360,-0.875377,7
8,2014-01-01,0,0,8,-0.071880,0.529586,21.937500,0.017243,0.262051,-1.560580,-0.745364,8
9,2014-01-01,0,0,9,-0.085246,0.454680,21.937500,0.016298,0.193370,-1.681703,-0.641496,9
10,2014-01-01,0,0,10,-0.106503,0.559188,21.937500,0.017921,0.192053,-2.120353,-0.670753,10
11,2014-01-01,0,0,11,-0.108499,0.723079,21.937500,0.020652,0.219294,-2.498713,-0.726946,11
12,2014-01-01,0,0,12,-0.103045,0.894661,21.937500,0.023380,0.255520,-2.523604,-0.708110,12
13,2014-01-01,0,0,13,-0.090523,0.985056,21.937500,0.024466,0.278049,-2.447816,-0.663536,13
14,2014-01-01,0,0,14,-0.079932,0.970665,21.937500,0.025253,0.276533,-2.059456,-0.584806,14
15,2014-01-01,0,0,15,-0.089138,1.193692,21.937500,0.044595,0.372942,-1.811628,-0.564681,15
16,2014-01-01,0,0,16,-0.098174,1.318444,21.937500,0.061771,0.436707,-1.782053,-0.590950,16
17,2014-01-01,0,0,17,-0.116340,1.362813,21.937500,0.108211,0.534814,-1.553986,-0.571100,17
18,2014-01-01,0,0,18,-0.107618,1.387715,21.937500,0.162781,0.587998,-1.254250,-0.448355,18
19,2014-01-01,0,0,19,-0.058687,1.497163,21.937500,0.224553,0.710863,-0.744611,-0.275406,19
20,2014-01-01,0,0,20,-0.002268,1.680235,21.937500,0.270848,0.938919,-0.177633,-0.073172,20
21,2014-01-01,0,0,21,0.064143,1.861143,21.937500,0.248254,1.013566,0.425403,0.240373,21
22,2014-01-01,0,0,22,0.089860,1.908235,21.937500,0.149271,0.798797,1.160533,0.456533,22
23,2014-01-01,0,0,23,0.070746,1.384849,21.937500,0.064127,0.555390,1.128348,0.487223,23
24,2014-01-01,0,1,0,0.257003,-0.463424,10.753906,-0.203649,-0.317740,0.444242,0.397781,0
25,2014-01-01,0,1,1,-0.216395,-0.567811,10.753906,-0.256615,-0.370850,-0.466197,-0.272063,1
26,2014-01-01,0,1,2,-0.573176,-0.498863,10.753906,-0.222981,-0.310965,-1.079969,-0.790796,2
27,2014-01-01,0,1,3,-0.772985,-0.288957,10.753906,-0.119492,-0.141554,-1.406850,-1.079718,3
28,2014-01-01,0,1,4,-0.944839,-0.099573,10.753906,-0.035197,0.000660,-1.713375,-1.330573,4
29,2014-01-01,0,1,5,-1.104920,0.028382,10.753906,0.012217,0.084690,-2.010287,-1.555887,5
...,...,...,...,...,...,...,...,...,...,...,...,...
5510010,2014-12-31,36,15,18,-3.945505,-11.385846,0.000000,-8.736362,-10.288864,-5.195920,-4.648630,8754
5510011,2014-12-31,36,15,19,-3.863202,-11.435539,0.000000,-8.785787,-10.349194,-5.085568,-4.550404,8755
5510012,2014-12-31,36,15,20,-3.790236,-11.469256,0.000000,-8.833356,-10.404244,-4.987692,-4.463492,8756
5510013,2014-12-31,36,15,21,-3.751216,-11.710610,0.000000,-9.034249,-10.651731,-4.954142,-4.422157,8757
5510014,2014-12-31,36,15,22,-3.759855,-11.949010,0.000000,-9.257728,-10.927852,-4.977774,-4.437751,8758
5510015,2014-12-31,36,15,23,-3.723328,-11.966019,0.000000,-9.328672,-11.001248,-4.915825,-4.391706,8759
5510016,2014-12-31,36,16,0,-4.346224,-5.462070,0.000000,-4.537033,-5.130517,-5.234953,-4.914418,8736
5510017,2014-12-31,36,16,1,-4.273223,-5.519116,0.000000,-4.586319,-5.185382,-5.151027,-4.833580,8737
5510018,2014-12-31,36,16,2,-4.176646,-5.534575,0.000000,-4.605758,-5.204578,-5.037656,-4.719765,8738
5510019,2014-12-31,36,16,3,-4.066040,-5.408746,0.000000,-4.511384,-5.087020,-4.893941,-4.586843,8739
5510020,2014-12-31,36,16,4,-3.882366,-5.394040,0.000000,-4.504385,-5.070832,-4.662072,-4.369967,8740
5510021,2014-12-31,36,16,5,-3.764228,-5.514014,0.000000,-4.598259,-5.177877,-4.523853,-4.240162,8741
5510022,2014-12-31,36,16,6,-3.737251,-5.732277,0.000000,-4.758860,-5.369090,-4.505898,-4.216031,8742
5510023,2014-12-31,36,16,7,-3.732038,-6.023784,0.000000,-4.972649,-5.626652,-4.523709,-4.220880,8743
5510024,2014-12-31,36,16,8,-3.731320,-6.344299,0.000000,-5.205656,-5.904937,-4.549109,-4.232682,8744
5510025,2014-12-31,36,16,9,-3.785414,-6.868059,0.000000,-5.585181,-6.365214,-4.656860,-4.315867,8745
5510026,2014-12-31,36,16,10,-3.864534,-7.517576,0.000000,-6.049275,-6.935678,-4.805822,-4.429798,8746
5510027,2014-12-31,36,16,11,-3.909679,-8.036030,0.000000,-6.414162,-7.383616,-4.902298,-4.501218,8747
5510028,2014-12-31,36,16,12,-3.948792,-8.379997,0.000000,-6.649499,-7.675812,-4.972927,-4.556769,8748
5510029,2014-12-31,36,16,13,-3.945142,-8.740491,0.000000,-6.895862,-7.978916,-4.986800,-4.565145,8749
5510030,2014-12-31,36,16,14,-3.862156,-9.294232,0.000000,-7.275239,-8.448806,-4.912259,-4.484384,8750
5510031,2014-12-31,36,16,15,-3.761739,-9.921757,0.000000,-7.704218,-8.985795,-4.824363,-4.387268,8751
5510032,2014-12-31,36,16,16,-3.738732,-10.483768,0.000000,-8.081091,-9.463417,-4.836672,-4.377504,8752
5510033,2014-12-31,36,16,17,-3.720183,-10.953524,0.000000,-8.406256,-9.875971,-4.851181,-4.369729,8753
5510034,2014-12-31,36,16,18,-3.644724,-11.268659,0.000000,-8.634800,-10.163864,-4.779905,-4.289255,8754
5510035,2014-12-31,36,16,19,-3.535077,-11.384758,0.000000,-8.738912,-10.282787,-4.642209,-4.160756,8755
5510036,2014-12-31,36,16,20,-3.436721,-11.426288,0.000000,-8.786481,-10.341744,-4.507223,-4.043571,8756
5510037,2014-12-31,36,16,21,-3.368404,-11.683267,0.000000,-8.995187,-10.597044,-4.442423,-3.968055,8757
5510038,2014-12-31,36,16,22,-3.352629,-12.027135,0.000000,-9.292884,-10.974727,-4.450430,-3.958259,8758
5510039,2014-12-31,36,16,23,-3.286805,-12.173050,0.000000,-9.457579,-11.169217,-4.363091,-3.879988,8759

## Converting the timeformat to ISO 8601

In [21]:
def converting_timeformat_to_ISO8601(row):
    """Generates datetime according to ISO 8601 (UTC)"""
    date = dateutil.parser.parse(row['date'])
    hour = int(row['time'])
    # timedelta from the datetime module enables the programmer 
    # to add time to a date. 
    date_time = date + timedelta(hours = hour)
    return str(date_time.isoformat()) + 'Z'  # MERRA2 datasets have UTC time zone.
df_wind['date_utc'] = df_wind.apply(converting_timeformat_to_ISO8601, axis=1)

df_wind['date_utc']

# execution time approx. 3+ min

0          2014-01-01T00:00:00Z
1          2014-01-01T01:00:00Z
2          2014-01-01T02:00:00Z
3          2014-01-01T03:00:00Z
4          2014-01-01T04:00:00Z
5          2014-01-01T05:00:00Z
6          2014-01-01T06:00:00Z
7          2014-01-01T07:00:00Z
8          2014-01-01T08:00:00Z
9          2014-01-01T09:00:00Z
10         2014-01-01T10:00:00Z
11         2014-01-01T11:00:00Z
12         2014-01-01T12:00:00Z
13         2014-01-01T13:00:00Z
14         2014-01-01T14:00:00Z
15         2014-01-01T15:00:00Z
16         2014-01-01T16:00:00Z
17         2014-01-01T17:00:00Z
18         2014-01-01T18:00:00Z
19         2014-01-01T19:00:00Z
20         2014-01-01T20:00:00Z
21         2014-01-01T21:00:00Z
22         2014-01-01T22:00:00Z
23         2014-01-01T23:00:00Z
24         2014-01-01T00:00:00Z
25         2014-01-01T01:00:00Z
26         2014-01-01T02:00:00Z
27         2014-01-01T03:00:00Z
28         2014-01-01T04:00:00Z
29         2014-01-01T05:00:00Z
                   ...
5510010    2014-12-31T18:00:00Z
5510011    2014-12-31T19:00:00Z
5510012    2014-12-31T20:00:00Z
5510013    2014-12-31T21:00:00Z
5510014    2014-12-31T22:00:00Z
5510015    2014-12-31T23:00:00Z
5510016    2014-12-31T00:00:00Z
5510017    2014-12-31T01:00:00Z
5510018    2014-12-31T02:00:00Z
5510019    2014-12-31T03:00:00Z
5510020    2014-12-31T04:00:00Z
5510021    2014-12-31T05:00:00Z
5510022    2014-12-31T06:00:00Z
5510023    2014-12-31T07:00:00Z
5510024    2014-12-31T08:00:00Z
5510025    2014-12-31T09:00:00Z
5510026    2014-12-31T10:00:00Z
5510027    2014-12-31T11:00:00Z
5510028    2014-12-31T12:00:00Z
5510029    2014-12-31T13:00:00Z
5510030    2014-12-31T14:00:00Z
5510031    2014-12-31T15:00:00Z
5510032    2014-12-31T16:00:00Z
5510033    2014-12-31T17:00:00Z
5510034    2014-12-31T18:00:00Z
5510035    2014-12-31T19:00:00Z
5510036    2014-12-31T20:00:00Z
5510037    2014-12-31T21:00:00Z
5510038    2014-12-31T22:00:00Z
5510039    2014-12-31T23:00:00Z
Name: date_utc, Length: 5510040, dtype: object

## Converting wind vectors to wind speed

This part uses the given wind vectors in the MERRA-2 original data to calculate a wind speed (vector addition).

In [22]:
def calculate_windspeed(d_frame, idx_u, idx_v):
    """
    Calculates the windspeed. The returned unit is m/s
    """
    um = float(d_frame[idx_u])
    vm = float(d_frame[idx_v])
    speed = math.sqrt((um ** 2) + (vm ** 2))
    return round(speed, 2)

# partial is used to create a function with pre-set arguments. 
calc_windspeed_2m = partial(calculate_windspeed, idx_u='U2M', idx_v='V2M')
calc_windspeed_10m = partial(calculate_windspeed, idx_u='U10M', idx_v='V10M')
calc_windspeed_50m = partial(calculate_windspeed, idx_u='U50M', idx_v='V50M')

df_wind['v_2m'] = df_wind.apply(calc_windspeed_2m, axis=1)
df_wind['v_10m']= df_wind.apply(calc_windspeed_10m, axis=1)
df_wind['v_50m'] = df_wind.apply(calc_windspeed_50m, axis=1)
df_wind

# execution time approx. 3 min

,date,lat,lon,time,U2M,V50M,DISPH,V2M,V10M,U50M,U10M,date_time_hours,date_utc,v_2m,v_10m,v_50m
0,2014-01-01,0,0,0,0.038314,-0.413376,21.937500,0.002162,-0.175894,0.312650,0.212723,0,2014-01-01T00:00:00Z,0.04,0.28,0.52
1,2014-01-01,0,0,1,0.001318,-0.492615,21.937500,-0.002465,-0.176514,-0.509410,-0.191207,1,2014-01-01T01:00:00Z,0.00,0.26,0.71
2,2014-01-01,0,0,2,-0.032648,-0.270592,21.937500,-0.000080,-0.061454,-1.062879,-0.500116,2,2014-01-01T02:00:00Z,0.03,0.50,1.10
3,2014-01-01,0,0,3,-0.046789,-0.008683,21.937500,0.008438,0.074510,-1.284535,-0.624029,3,2014-01-01T03:00:00Z,0.05,0.63,1.28
4,2014-01-01,0,0,4,-0.059219,0.166052,21.937500,0.012166,0.158131,-1.457027,-0.721930,4,2014-01-01T04:00:00Z,0.06,0.74,1.47
5,2014-01-01,0,0,5,-0.074952,0.260315,21.937500,0.010508,0.187717,-1.690463,-0.830301,5,2014-01-01T05:00:00Z,0.08,0.85,1.71
6,2014-01-01,0,0,6,-0.086912,0.456126,21.937500,0.015211,0.253542,-1.856832,-0.899296,6,2014-01-01T06:00:00Z,0.09,0.93,1.91
7,2014-01-01,0,0,7,-0.084374,0.576638,21.937500,0.018128,0.292173,-1.829360,-0.875377,7,2014-01-01T07:00:00Z,0.09,0.92,1.92
8,2014-01-01,0,0,8,-0.071880,0.529586,21.937500,0.017243,0.262051,-1.560580,-0.745364,8,2014-01-01T08:00:00Z,0.07,0.79,1.65
9,2014-01-01,0,0,9,-0.085246,0.454680,21.937500,0.016298,0.193370,-1.681703,-0.641496,9,2014-01-01T09:00:00Z,0.09,0.67,1.74
10,2014-01-01,0,0,10,-0.106503,0.559188,21.937500,0.017921,0.192053,-2.120353,-0.670753,10,2014-01-01T10:00:00Z,0.11,0.70,2.19
11,2014-01-01,0,0,11,-0.108499,0.723079,21.937500,0.020652,0.219294,-2.498713,-0.726946,11,2014-01-01T11:00:00Z,0.11,0.76,2.60
12,2014-01-01,0,0,12,-0.103045,0.894661,21.937500,0.023380,0.255520,-2.523604,-0.708110,12,2014-01-01T12:00:00Z,0.11,0.75,2.68
13,2014-01-01,0,0,13,-0.090523,0.985056,21.937500,0.024466,0.278049,-2.447816,-0.663536,13,2014-01-01T13:00:00Z,0.09,0.72,2.64
14,2014-01-01,0,0,14,-0.079932,0.970665,21.937500,0.025253,0.276533,-2.059456,-0.584806,14,2014-01-01T14:00:00Z,0.08,0.65,2.28
15,2014-01-01,0,0,15,-0.089138,1.193692,21.937500,0.044595,0.372942,-1.811628,-0.564681,15,2014-01-01T15:00:00Z,0.10,0.68,2.17
16,2014-01-01,0,0,16,-0.098174,1.318444,21.937500,0.061771,0.436707,-1.782053,-0.590950,16,2014-01-01T16:00:00Z,0.12,0.73,2.22
17,2014-01-01,0,0,17,-0.116340,1.362813,21.937500,0.108211,0.534814,-1.553986,-0.571100,17,2014-01-01T17:00:00Z,0.16,0.78,2.07
18,2014-01-01,0,0,18,-0.107618,1.387715,21.937500,0.162781,0.587998,-1.254250,-0.448355,18,2014-01-01T18:00:00Z,0.20,0.74,1.87
19,2014-01-01,0,0,19,-0.058687,1.497163,21.937500,0.224553,0.710863,-0.744611,-0.275406,19,2014-01-01T19:00:00Z,0.23,0.76,1.67
20,2014-01-01,0,0,20,-0.002268,1.680235,21.937500,0.270848,0.938919,-0.177633,-0.073172,20,2014-01-01T20:00:00Z,0.27,0.94,1.69
21,2014-01-01,0,0,21,0.064143,1.861143,21.937500,0.248254,1.013566,0.425403,0.240373,21,2014-01-01T21:00:00Z,0.26,1.04,1.91
22,2014-01-01,0,0,22,0.089860,1.908235,21.937500,0.149271,0.798797,1.160533,0.456533,22,2014-01-01T22:00:00Z,0.17,0.92,2.23
23,2014-01-01,0,0,23,0.070746,1.384849,21.937500,0.064127,0.555390,1.128348,0.487223,23,2014-01-01T23:00:00Z,0.10,0.74,1.79
24,2014-01-01,0,1,0,0.257003,-0.463424,10.753906,-0.203649,-0.317740,0.444242,0.397781,0,2014-01-01T00:00:00Z,0.33,0.51,0.64
25,2014-01-01,0,1,1,-0.216395,-0.567811,10.753906,-0.256615,-0.370850,-0.466197,-0.272063,1,2014-01-01T01:00:00Z,0.34,0.46,0.73
26,2014-01-01,0,1,2,-0.573176,-0.498863,10.753906,-0.222981,-0.310965,-1.079969,-0.790796,2,2014-01-01T02:00:00Z,0.62,0.85,1.19
27,2014-01-01,0,1,3,-0.772985,-0.288957,10.753906,-0.119492,-0.141554,-1.406850,-1.079718,3,2014-01-01T03:00:00Z,0.78,1.09,1.44
28,2014-01-01,0,1,4,-0.944839,-0.099573,10.753906,-0.035197,0.000660,-1.713375,-1.330573,4,2014-01-01T04:00:00Z,0.95,1.33,1.72
29,2014-01-01,0,1,5,-1.104920,0.028382,10.753906,0.012217,0.084690,-2.010287,-1.555887,5,2014-01-01T05:00:00Z,1.10,1.56,2.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5510010,2014-12-31,36,15,18,-3.945505,-11.385846,0.000000,-8.736362,-10.288864,-5.195920,-4.648630,8754,2014-12-31T18:00:00Z,9.59,11.29,12.52
5510011,2014-12-31,36,15,19,-3.863202,-11.435539,0.000000,-8.785787,-10.349194,-5.085568,-4.550404,8755,2014-12-31T19:00:00Z,9.60,11.31,12.52
5510012,2014-12-31,36,15,20,-3.790236,-11.469256,0.000000,-8.833356,-10.404244,-4.987692,-4.463492,8756,2014-12-31T20:00:00Z,9.61,11.32,12.51
5510013,2014-12-31,36,15,21,-3.751216,-11.710610,0.000000,-9.034249,-10.651731,-4.954142,-4.422157,8757,2014-12-31T21:00:00Z,9.78,11.53,12.72
5510014,2014-12-31,36,15,22,-3.759855,-11.949010,0.000000,-9.257728,-10.927852,-4.977774,-4.437751,8758,2014-12-31T22:00:00Z,9.99,11.79,12.94
5510015,2014-12-31,36,15,23,-3.723328,-11.966019,0.000000,-9.328672,-11.001248,-4.915825,-4.391706,8759,2014-12-31T23:00:00Z,10.04,11.85,12.94
5510016,2014-12-31,36,16,0,-4.346224,-5.462070,0.000000,-4.537033,-5.130517,-5.234953,-4.914418,8736,2014-12-31T00:00:00Z,6.28,7.10,7.57
5510017,2014-12-31,36,16,1,-4.273223,-5.519116,0.000000,-4.586319,-5.185382,-5.151027,-4.833580,8737,2014-12-31T01:00:00Z,6.27,7.09,7.55
5510018,2014-12-31,36,16,2,-4.176646,-5.534575,0.000000,-4.605758,-5.204578,-5.037656,-4.719765,8738,2014-12-31T02:00:00Z,6.22,7.03,7.48
5510019,2014-12-31,36,16,3,-4.066040,-5.408746,0.000000,-4.511384,-5.087020,-4.893941,-4.586843,8739,2014-12-31T03:00:00Z,6.07,6.85,7.29
5510020,2014-12-31,36,16,4,-3.882366,-5.394040,0.000000,-4.504385,-5.070832,-4.662072,-4.369967,8740,2014-12-31T04:00:00Z,5.95,6.69,7.13
5510021,2014-12-31,36,16,5,-3.764228,-5.514014,0.000000,-4.598259,-5.177877,-4.523853,-4.240162,8741,2014-12-31T05:00:00Z,5.94,6.69,7.13
5510022,2014-12-31,36,16,6,-3.737251,-5.732277,0.000000,-4.758860,-5.369090,-4.505898,-4.216031,8742,2014-12-31T06:00:00Z,6.05,6.83,7.29
5510023,2014-12-31,36,16,7,-3.732038,-6.023784,0.000000,-4.972649,-5.626652,-4.523709,-4.220880,8743,2014-12-31T07:00:00Z,6.22,7.03,7.53
5510024,2014-12-31,36,16,8,-3.731320,-6.344299,0.000000,-5.205656,-5.904937,-4.549109,-4.232682,8744,2014-12-31T08:00:00Z,6.40,7.27,7.81
5510025,2014-12-31,36,16,9,-3.785414,-6.868059,0.000000,-5.585181,-6.365214,-4.656860,-4.315867,8745,2014-12-31T09:00:00Z,6.75,7.69,8.30
5510026,2014-12-31,36,16,10,-3.864534,-7.517576,0.000000,-6.049275,-6.935678,-4.805822,-4.429798,8746,2014-12-31T10:00:00Z,7.18,8.23,8.92
5510027,2014-12-31,36,16,11,-3.909679,-8.036030,0.000000,-6.414162,-7.383616,-4.902298,-4.501218,8747,2014-12-31T11:00:00Z,7.51,8.65,9.41
5510028,2014-12-31,36,16,12,-3.948792,-8.379997,0.000000,-6.649499,-7.675812,-4.972927,-4.556769,8748,2014-12-31T12:00:00Z,7.73,8.93,9.74
5510029,2014-12-31,36,16,13,-3.945142,-8.740491,0.000000,-6.895862,-7.978916,-4.986800,-4.565145,8749,2014-12-31T13:00:00Z,7.94,9.19,10.06
5510030,2014-12-31,36,16,14,-3.862156,-9.294232,0.000000,-7.275239,-8.448806,-4.912259,-4.484384,8750,2014-12-31T14:00:00Z,8.24,9.57,10.51
5510031,2014-12-31,36,16,15,-3.761739,-9.921757,0.000000,-7.704218,-8.985795,-4.824363,-4.387268,8751,2014-12-31T15:00:00Z,8.57,10.00,11.03
5510032,2014-12-31,36,16,16,-3.738732,-10.483768,0.000000,-8.081091,-9.463417,-4.836672,-4.377504,8752,2014-12-31T16:00:00Z,8.90,10.43,11.55
5510033,2014-12-31,36,16,17,-3.720183,-10.953524,0.000000,-8.406256,-9.875971,-4.851181,-4.369729,8753,2014-12-31T17:00:00Z,9.19,10.80,11.98
5510034,2014-12-31,36,16,18,-3.644724,-11.268659,0.000000,-8.634800,-10.163864,-4.779905,-4.289255,8754,2014-12-31T18:00:00Z,9.37,11.03,12.24
5510035,2014-12-31,36,16,19,-3.535077,-11.384758,0.000000,-8.738912,-10.282787,-4.642209,-4.160756,8755,2014-12-31T19:00:00Z,9.43,11.09,12.29
5510036,2014-12-31,36,16,20,-3.436721,-11.426288,0.000000,-8.786481,-10.341744,-4.507223,-4.043571,8756,2014-12-31T20:00:00Z,9.43,11.10,12.28
5510037,2014-12-31,36,16,21,-3.368404,-11.683267,0.000000,-8.995187,-10.597044,-4.442423,-3.968055,8757,2014-12-31T21:00:00Z,9.61,11.32,12.50
5510038,2014-12-31,36,16,22,-3.352629,-12.027135,0.000000,-9.292884,-10.974727,-4.450430,-3.958259,8758,2014-12-31T22:00:00Z,9.88,11.67,12.82
5510039,2014-12-31,36,16,23,-3.286805,-12.173050,0.000000,-9.457579,-11.169217,-4.363091,-3.879988,8759,2014-12-31T23:00:00Z,10.01,11.82,12.93

## Setting up data Frame for roughness, radiation, temperature and air parameters

In [23]:
file_path = os.path.join('download_roughness', '*.nc4')
with xr.open_mfdataset(file_path, concat_dim='date', 
                       preprocess=extract_date) as ds_rough:
    df_rough = ds_rough.to_dataframe()

df_rough.reset_index(inplace=True)

In [24]:
file_path = os.path.join('download_radiation', '*.nc4')
try:
    with xr.open_mfdataset(file_path, concat_dim='date',
                           preprocess=extract_date) as ds_rad:
        print(ds_rad)
        df_rad = ds_rad.to_dataframe()

except xr.MergeError as e:
    print(e)
df_rad.reset_index(inplace=True)

<xarray.Dataset>
Dimensions:  (date: 365, lat: 37, lon: 17, time: 24)
Coordinates:
  * date     (date) <U10 '2014-01-01' '2014-01-02' '2014-01-03' '2014-01-04' ...
Dimensions without coordinates: lat, lon, time
Data variables:
    SWTDN    (date, time, lat, lon) float64 689.2 700.8 712.2 723.8 735.0 ...
    SWGDN    (date, time, lat, lon) float64 421.8 364.2 305.1 304.6 315.4 ...
Attributes:
    History:                           Original file generated: Mon Dec  8 12...
    Comment:                           GMAO filename: d5124_m2_jan10.tavg1_2d...
    Filename:                          MERRA2_400.tavg1_2d_rad_Nx.20140101.nc4
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    Format:                            NetCDF-4/HDF-5
    SpatialCoverage:                   global
    VersionID:                         5.12.4
    TemporalRange:                     1980-01-01 -> 2016-12-31
    identifier_product_doi_authority:  http://dx.doi.org/
    ShortName:                         M2T1NXRAD
    GranuleID:                         MERRA2_400.tavg1_2d_rad_Nx.20140101.nc4
    ProductionDateTime:                Original file generated: Mon Dec  8 12...
    LongName:                          MERRA2 tavg1_2d_rad_Nx: 2d,1-Hourly,Ti...
    Title:                             MERRA2 tavg1_2d_rad_Nx: 2d,1-Hourly,Ti...
    SouthernmostLatitude:              -90.0
    NorthernmostLatitude:              90.0
    WesternmostLongitude:              -180.0
    EasternmostLongitude:              179.375
    LatitudeResolution:                0.5
    LongitudeResolution:               0.625
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/Q9QMY5PBNV1T
    RangeBeginningDate:                2014-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   2014-01-01
    RangeEndingTime:                   23:59:59.000000
    DODS_EXTRA.Unlimited_Dimension:    time
    history:                           2017-12-18 13:17:34 GMT Hyrax-1.13.4 h...

In [25]:
file_path = os.path.join('download_temperature', '*.nc4')
try:
    with xr.open_mfdataset(file_path, concat_dim='date',
                           preprocess=extract_date) as ds_temp:
        print(ds_temp)
        df_temp = ds_temp.to_dataframe()

except xr.MergeError as e:
    print(e)
df_temp.reset_index(inplace=True)

<xarray.Dataset>
Dimensions:  (date: 365, lat: 37, lon: 17, time: 24)
Coordinates:
  * date     (date) <U10 '2014-01-01' '2014-01-02' '2014-01-03' '2014-01-04' ...
Dimensions without coordinates: lat, lon, time
Data variables:
    T2M      (date, time, lat, lon) float64 297.1 298.9 300.2 300.5 301.2 ...
Attributes:
    History:                           Original file generated: Mon Dec  8 12...
    Comment:                           GMAO filename: d5124_m2_jan10.tavg1_2d...
    Filename:                          MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    Format:                            NetCDF-4/HDF-5
    SpatialCoverage:                   global
    VersionID:                         5.12.4
    TemporalRange:                     1980-01-01 -> 2016-12-31
    identifier_product_doi_authority:  http://dx.doi.org/
    ShortName:                         M2T1NXSLV
    GranuleID:                         MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    ProductionDateTime:                Original file generated: Mon Dec  8 12...
    LongName:                          MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    Title:                             MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    SouthernmostLatitude:              -90.0
    NorthernmostLatitude:              90.0
    WesternmostLongitude:              -180.0
    EasternmostLongitude:              179.375
    LatitudeResolution:                0.5
    LongitudeResolution:               0.625
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/VJAFPLI1CSIV
    RangeBeginningDate:                2014-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   2014-01-01
    RangeEndingTime:                   23:59:59.000000
    DODS_EXTRA.Unlimited_Dimension:    time
    history:                           2017-12-18 13:24:29 GMT Hyrax-1.13.4 h...

In [26]:
file_path = os.path.join('download_density', '*.nc4')
try:
    with xr.open_mfdataset(file_path, concat_dim='date',
                           preprocess=extract_date) as ds_dens:
        print(ds_dens)
        df_dens = ds_dens.to_dataframe()

except xr.MergeError as e:
    print(e)
df_dens.reset_index(inplace=True)

<xarray.Dataset>
Dimensions:  (date: 365, lat: 37, lon: 17, time: 24)
Coordinates:
  * date     (date) <U10 '2014-01-01' '2014-01-02' '2014-01-03' '2014-01-04' ...
Dimensions without coordinates: lat, lon, time
Data variables:
    RHOA     (date, time, lat, lon) float64 1.148 1.164 1.163 1.164 1.161 ...
Attributes:
    History:                           Original file generated: Mon Dec  8 12...
    Comment:                           GMAO filename: d5124_m2_jan10.tavg1_2d...
    Filename:                          MERRA2_400.tavg1_2d_flx_Nx.20140101.nc4
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    Format:                            NetCDF-4/HDF-5
    SpatialCoverage:                   global
    VersionID:                         5.12.4
    TemporalRange:                     1980-01-01 -> 2016-12-31
    identifier_product_doi_authority:  http://dx.doi.org/
    ShortName:                         M2T1NXFLX
    GranuleID:                         MERRA2_400.tavg1_2d_flx_Nx.20140101.nc4
    ProductionDateTime:                Original file generated: Mon Dec  8 12...
    LongName:                          MERRA2 tavg1_2d_flx_Nx: 2d,1-Hourly,Ti...
    Title:                             MERRA2 tavg1_2d_flx_Nx: 2d,1-Hourly,Ti...
    SouthernmostLatitude:              -90.0
    NorthernmostLatitude:              90.0
    WesternmostLongitude:              -180.0
    EasternmostLongitude:              179.375
    LatitudeResolution:                0.5
    LongitudeResolution:               0.625
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/7MCPBJ41Y0K6
    RangeBeginningDate:                2014-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   2014-01-01
    RangeEndingTime:                   23:59:59.000000
    DODS_EXTRA.Unlimited_Dimension:    time
    history:                           2017-12-18 13:33:27 GMT Hyrax-1.13.4 h...

In [27]:
file_path = os.path.join('download_pressure', '*.nc4')
try:
    with xr.open_mfdataset(file_path, concat_dim='date',
                           preprocess=extract_date) as ds_pres:
        print(ds_pres)
        df_pres = ds_pres.to_dataframe()

except xr.MergeError as e:
    print(e)
df_pres.reset_index(inplace=True)

<xarray.Dataset>
Dimensions:  (date: 365, lat: 37, lon: 17, time: 24)
Coordinates:
  * date     (date) <U10 '2014-01-01' '2014-01-02' '2014-01-03' '2014-01-04' ...
Dimensions without coordinates: lat, lon, time
Data variables:
    PS       (date, time, lat, lon) float64 9.866e+04 1.007e+05 1.01e+05 ...
Attributes:
    History:                           Original file generated: Mon Dec  8 12...
    Comment:                           GMAO filename: d5124_m2_jan10.tavg1_2d...
    Filename:                          MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    Format:                            NetCDF-4/HDF-5
    SpatialCoverage:                   global
    VersionID:                         5.12.4
    TemporalRange:                     1980-01-01 -> 2016-12-31
    identifier_product_doi_authority:  http://dx.doi.org/
    ShortName:                         M2T1NXSLV
    GranuleID:                         MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4
    ProductionDateTime:                Original file generated: Mon Dec  8 12...
    LongName:                          MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    Title:                             MERRA2 tavg1_2d_slv_Nx: 2d,1-Hourly,Ti...
    SouthernmostLatitude:              -90.0
    NorthernmostLatitude:              90.0
    WesternmostLongitude:              -180.0
    EasternmostLongitude:              179.375
    LatitudeResolution:                0.5
    LongitudeResolution:               0.625
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/VJAFPLI1CSIV
    RangeBeginningDate:                2014-01-01
    RangeBeginningTime:                00:00:00.000000
    RangeEndingDate:                   2014-01-01
    RangeEndingTime:                   23:59:59.000000
    DODS_EXTRA.Unlimited_Dimension:    time
    history:                           2017-12-18 13:41:53 GMT Hyrax-1.13.4 h...

## Combining the data Frames

In [28]:
df = pd.merge(df_wind, df_rough, on=['date', 'lat', 'lon', 'time'])
df = pd.merge(df, df_rad, on=['date', 'lat', 'lon', 'time'])
df = pd.merge(df, df_temp, on=['date', 'lat', 'lon', 'time'])
df = pd.merge(df, df_dens, on=['date', 'lat', 'lon', 'time'])
df = pd.merge(df, df_pres, on=['date', 'lat', 'lon', 'time'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5510040 entries, 0 to 5510039
Data columns (total 22 columns):
date               object
lat                int64
lon                int64
time               int64
U2M                float64
V50M               float64
DISPH              float64
V2M                float64
V10M               float64
U50M               float64
U10M               float64
date_time_hours    int64
date_utc           object
v_2m               float64
v_10m              float64
v_50m              float64
Z0M                float64
SWTDN              float64
SWGDN              float64
T2M                float64
RHOA               float64
PS                 float64
dtypes: float64(16), int64(4), object(2)
memory usage: 966.9+ MB

---
# Structure the dataframe, add and remove columns

## Calculating the displacement height

The so-called "displacement height" is the height
> _"[...] at which zero wind speed is achieved as a result of flow obstacles such as trees or buildings. It is generally approximated as 2/3 of the average height of the obstacles. For example, if estimating winds over a forest canopy of height h = 30 m, the zero-plane displacement would be d = 20 m."_ ([Source](https://en.wikipedia.org/wiki/Log_wind_profile#Definition))

In [29]:
# Calculate height for h1 (displacement height +2m) and h2 (displacement height
# +10m).
df['h1'] = df.apply((lambda x:int(x['DISPH']) + 2), axis=1)
df['h2'] = df.apply((lambda x:int(x['DISPH']) + 10), axis=1)

## Adding needed and removing not needed columns

In [30]:
df.drop('DISPH', axis=1, inplace=True)
df.drop(['time', 'date'], axis=1, inplace=True)
df.drop(['U2M', 'U10M', 'U50M', 'V2M', 'V10M', 'V50M'], axis=1, inplace=True)

df['lat'] = df['lat'].apply(lambda x: lat_array[int(x)])
df['lon'] = df['lon'].apply(lambda x: lon_array[int(x)])

## Renaming and sorting columns

In [31]:
rename_map = {'date_time_hours': 'cumulated hours', 
              'date_utc': 'timestamp',
              'v_2m': 'v1', 
              'v_10m': 'v2', 
              'Z0M': 'z0',
              'T2M': 'T',
              'RHOA': 'rho',
              'PS': 'p'
             }

df.rename(columns=rename_map, inplace=True)

In [32]:
# Change order of the columns
columns = ['timestamp', 'cumulated hours', 'lat', 'lon',
        'v1', 'v2', 'v_50m',
        'h1', 'h2', 'z0', 'SWTDN', 'SWGDN', 'T', 'rho', 'p']
df = df[columns]

## First look at the final data Frame

### structure and format

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5510040 entries, 0 to 5510039
Data columns (total 15 columns):
timestamp          object
cumulated hours    int64
lat                float64
lon                float64
v1                 float64
v2                 float64
v_50m              float64
h1                 int64
h2                 int64
z0                 float64
SWTDN              float64
SWGDN              float64
T                  float64
rho                float64
p                  float64
dtypes: float64(11), int64(3), object(1)
memory usage: 672.6+ MB

### resulting dataframe

In [34]:
df

,timestamp,cumulated hours,lat,lon,v1,v2,v_50m,h1,h2,z0,SWTDN,SWGDN,T,rho,p
0,2014-01-01T00:00:00Z,0,4.0,116.875,0.04,0.28,0.52,23,31,4.322270,689.250000,421.750000,297.120544,1.148419,98662.414062
1,2014-01-01T01:00:00Z,1,4.0,116.875,0.00,0.26,0.71,23,31,4.322270,939.750000,611.500000,299.075836,1.142164,98667.718750
2,2014-01-01T02:00:00Z,2,4.0,116.875,0.03,0.50,1.10,23,31,4.322270,1123.500000,740.000000,300.449768,1.136918,98630.703125
3,2014-01-01T03:00:00Z,3,4.0,116.875,0.05,0.63,1.28,23,31,4.322270,1228.500000,797.250000,301.194031,1.133301,98564.273438
4,2014-01-01T04:00:00Z,4,4.0,116.875,0.06,0.74,1.47,23,31,4.322270,1247.000000,776.500000,301.486328,1.130882,98469.789062
5,2014-01-01T05:00:00Z,5,4.0,116.875,0.08,0.85,1.71,23,31,4.322270,1177.500000,647.750000,301.368988,1.129341,98376.828125
6,2014-01-01T06:00:00Z,6,4.0,116.875,0.09,0.93,1.91,23,31,4.322270,1025.500000,473.375000,300.977020,1.128992,98307.757812
7,2014-01-01T07:00:00Z,7,4.0,116.875,0.09,0.92,1.92,23,31,4.322270,801.000000,334.250000,300.518066,1.129730,98301.656250
8,2014-01-01T08:00:00Z,8,4.0,116.875,0.07,0.79,1.65,23,31,4.322270,519.000000,172.937500,299.967255,1.131219,98321.734375
9,2014-01-01T09:00:00Z,9,4.0,116.875,0.09,0.67,1.74,23,31,4.322270,199.250000,51.296875,299.282684,1.133268,98380.125000
10,2014-01-01T10:00:00Z,10,4.0,116.875,0.11,0.70,2.19,23,31,4.322270,1.564453,0.201233,298.477081,1.135451,98444.500000
11,2014-01-01T11:00:00Z,11,4.0,116.875,0.11,0.76,2.60,23,31,4.322270,0.000000,0.000000,297.984314,1.137363,98522.007812
12,2014-01-01T12:00:00Z,12,4.0,116.875,0.11,0.75,2.68,23,31,4.322270,0.000000,0.000000,297.672180,1.139069,98588.828125
13,2014-01-01T13:00:00Z,13,4.0,116.875,0.09,0.72,2.64,23,31,4.322270,0.000000,0.000000,297.406250,1.140646,98614.125000
14,2014-01-01T14:00:00Z,14,4.0,116.875,0.08,0.65,2.28,23,31,4.322270,0.000000,0.000000,297.142334,1.141824,98596.250000
15,2014-01-01T15:00:00Z,15,4.0,116.875,0.10,0.68,2.17,23,31,4.322270,0.000000,0.000000,296.855713,1.142306,98561.101562
16,2014-01-01T16:00:00Z,16,4.0,116.875,0.12,0.73,2.22,23,31,4.322270,0.000000,0.000000,296.617493,1.142741,98512.578125
17,2014-01-01T17:00:00Z,17,4.0,116.875,0.16,0.78,2.07,23,31,4.322270,0.000000,0.000000,296.459290,1.142946,98454.726562
18,2014-01-01T18:00:00Z,18,4.0,116.875,0.20,0.74,1.87,23,31,4.322270,0.000000,0.000000,296.299438,1.143020,98405.671875
19,2014-01-01T19:00:00Z,19,4.0,116.875,0.23,0.76,1.67,23,31,4.322270,0.000000,0.000000,296.158936,1.143462,98401.890625
20,2014-01-01T20:00:00Z,20,4.0,116.875,0.27,0.94,1.69,23,31,4.322270,0.000000,0.000000,295.985199,1.144065,98436.679688
21,2014-01-01T21:00:00Z,21,4.0,116.875,0.26,1.04,1.91,23,31,4.322270,0.000000,0.000000,295.820648,1.144793,98483.601562
22,2014-01-01T22:00:00Z,22,4.0,116.875,0.17,0.92,2.23,23,31,4.322270,77.562500,15.761719,295.754456,1.145904,98564.179688
23,2014-01-01T23:00:00Z,23,4.0,116.875,0.10,0.74,1.79,23,31,4.322270,389.500000,127.062500,296.837189,1.146885,98658.421875
24,2014-01-01T00:00:00Z,0,4.0,117.500,0.33,0.51,0.64,12,20,2.118169,700.750000,364.250000,298.917419,1.164350,100726.414062
25,2014-01-01T01:00:00Z,1,4.0,117.500,0.34,0.46,0.73,12,20,2.118169,949.000000,516.500000,299.958649,1.161329,100739.718750
26,2014-01-01T02:00:00Z,2,4.0,117.500,0.62,0.85,1.19,12,20,2.118169,1129.500000,623.500000,301.082581,1.157487,100702.703125
27,2014-01-01T03:00:00Z,3,4.0,117.500,0.78,1.09,1.44,12,20,2.118169,1231.000000,674.000000,301.623718,1.154968,100636.273438
28,2014-01-01T04:00:00Z,4,4.0,117.500,0.95,1.33,1.72,12,20,2.118169,1245.500000,642.000000,301.767578,1.153343,100557.789062
29,2014-01-01T05:00:00Z,5,4.0,117.500,1.10,1.56,2.01,12,20,2.118169,1173.000000,579.750000,301.798676,1.151863,100472.828125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5510010,2014-12-31T18:00:00Z,8754,22.0,126.250,9.59,11.29,12.52,2,10,0.000786,0.000000,0.000000,294.919434,1.204499,101947.429688
5510011,2014-12-31T19:00:00Z,8755,22.0,126.250,9.60,11.31,12.52,2,10,0.000789,0.000000,0.000000,294.831177,1.205313,101966.570312
5510012,2014-12-31T20:00:00Z,8756,22.0,126.250,9.61,11.32,12.51,2,10,0.000792,0.000000,0.000000,294.730133,1.206417,102017.351562
5510013,2014-12-31T21:00:00Z,8757,22.0,126.250,9.78,11.53,12.72,2,10,0.000828,0.000000,0.000000,294.553070,1.208134,102088.210938
5510014,2014-12-31T22:00:00Z,8758,22.0,126.250,9.99,11.79,12.94,2,10,0.000873,87.031250,28.078125,294.254089,1.210702,102184.406250
5510015,2014-12-31T23:00:00Z,8759,22.0,126.250,10.04,11.85,12.94,2,10,0.000885,369.125000,98.281250,293.902557,1.213971,102286.578125
5510016,2014-12-31T00:00:00Z,8736,22.0,126.875,6.28,7.10,7.57,2,10,0.000295,629.500000,252.750000,294.514557,1.207187,102063.546875
5510017,2014-12-31T01:00:00Z,8737,22.0,126.875,6.27,7.09,7.55,2,10,0.000294,822.500000,522.500000,294.548920,1.207032,102065.210938
5510018,2014-12-31T02:00:00Z,8738,22.0,126.875,6.22,7.03,7.48,2,10,0.000289,945.250000,644.000000,294.568146,1.206364,102013.335938
5510019,2014-12-31T03:00:00Z,8739,22.0,126.875,6.07,6.85,7.29,2,10,0.000275,989.500000,634.000000,294.584442,1.205274,101934.187500
5510020,2014-12-31T04:00:00Z,8740,22.0,126.875,5.95,6.69,7.13,2,10,0.000262,952.250000,639.250000,294.616669,1.204083,101855.578125
5510021,2014-12-31T05:00:00Z,8741,22.0,126.875,5.94,6.69,7.13,2,10,0.000262,835.750000,611.500000,294.669373,1.203184,101812.132812
5510022,2014-12-31T06:00:00Z,8742,22.0,126.875,6.05,6.83,7.29,2,10,0.000272,648.250000,447.375000,294.743256,1.202906,101807.585938
5510023,2014-12-31T07:00:00Z,8743,22.0,126.875,6.22,7.03,7.53,2,10,0.000288,402.500000,210.687500,294.817230,1.203008,101843.062500
5510024,2014-12-31T08:00:00Z,8744,22.0,126.875,6.40,7.27,7.81,2,10,0.000307,117.437500,45.843750,294.873108,1.203393,101896.398438
5510025,2014-12-31T09:00:00Z,8745,22.0,126.875,6.75,7.69,8.30,2,10,0.000344,0.000000,0.000000,294.889465,1.204135,101947.882812
5510026,2014-12-31T10:00:00Z,8746,22.0,126.875,7.18,8.23,8.92,2,10,0.000396,0.000000,0.000000,294.900940,1.204965,102008.265625
5510027,2014-12-31T11:00:00Z,8747,22.0,126.875,7.51,8.65,9.41,2,10,0.000438,0.000000,0.000000,294.897156,1.205524,102048.000000
5510028,2014-12-31T12:00:00Z,8748,22.0,126.875,7.73,8.93,9.74,2,10,0.000469,0.000000,0.000000,294.866638,1.205911,102063.210938
5510029,2014-12-31T13:00:00Z,8749,22.0,126.875,7.94,9.19,10.06,2,10,0.000499,0.000000,0.000000,294.836334,1.206069,102052.171875
5510030,2014-12-31T14:00:00Z,8750,22.0,126.875,8.24,9.57,10.51,2,10,0.000544,0.000000,0.000000,294.848358,1.205689,102026.343750
5510031,2014-12-31T15:00:00Z,8751,22.0,126.875,8.57,10.00,11.03,2,10,0.000598,0.000000,0.000000,294.912231,1.205176,102014.156250
5510032,2014-12-31T16:00:00Z,8752,22.0,126.875,8.90,10.43,11.55,2,10,0.000654,0.000000,0.000000,294.955963,1.204520,101987.781250
5510033,2014-12-31T17:00:00Z,8753,22.0,126.875,9.19,10.80,11.98,2,10,0.000706,0.000000,0.000000,294.967865,1.203787,101948.726562
5510034,2014-12-31T18:00:00Z,8754,22.0,126.875,9.37,11.03,12.24,2,10,0.000741,0.000000,0.000000,294.935059,1.203766,101923.429688
5510035,2014-12-31T19:00:00Z,8755,22.0,126.875,9.43,11.09,12.29,2,10,0.000751,0.000000,0.000000,294.846802,1.204459,101942.570312
5510036,2014-12-31T20:00:00Z,8756,22.0,126.875,9.43,11.10,12.28,2,10,0.000754,0.000000,0.000000,294.730133,1.205807,101993.351562
5510037,2014-12-31T21:00:00Z,8757,22.0,126.875,9.61,11.32,12.50,2,10,0.000788,0.000000,0.000000,294.623383,1.207157,102056.210938
5510038,2014-12-31T22:00:00Z,8758,22.0,126.875,9.88,11.67,12.82,2,10,0.000846,96.781250,33.312500,294.379089,1.209482,102152.406250
5510039,2014-12-31T23:00:00Z,8759,22.0,126.875,10.01,11.82,12.93,2,10,0.000876,380.500000,107.031250,294.004120,1.212628,102254.578125

---
# Saving data

## Save as CSV

In [35]:
df.to_csv('weather_data_GER_2016.csv', index=False)

## Save as SQLite

In [36]:
# Write the results to sqlite database. Using the chunksize parameter makes
# this cell not use so much memory. If the parameter is not set, the to_sql
# function will try to write all rows at the same time. This uses too much
# memory. If you have a lot of memory, you can remove the parameter or increase
# it to speed this process up. If you have memory problemes, try decreasing the
# chunksize.
engine = sqlalchemy.create_engine(
    'sqlite:///' + 'weather_data_GER_2016.sqlite')  

df.to_sql('weather_data_GER_2016',
             engine,
             if_exists="replace",
             chunksize=100000,
             index=False
             )

## Create metadata

In [37]:
# Here we define meta data of the resulting data package.
# The meta data follows the specification at:
# http://dataprotocols.org/data-packages/

metadata = """
name: opsd-weather-data
title: Weather data
long_description: >-
    Weather data differ significantly from the other data types used resp. 
    provided by OPSD in that the sheer size of the data packages greatly 
    exceeds OPSD's capacity to host them in a similar way as feed-in 
    timeseries, power plant data etc. While the other data packages also
    offer a complete one-klick download of the bundled data packages with 
    all relevant data this is impossible for weather datasets like MERRA-2 due 
    to their size (variety of variables, very long timespan, huge geographical
    coverage etc.). It would make no sense to mirror the data from the NASA 
    servers.
    Instead we choose to provide a documented methodological script 
    (as a kind of tutorial). The method describes one way to automatically 
    obtain the desired weather data from the MERRA-2 database and simplifies 
    resp. unifies alternative manual data obtaining methods in a single 
    script.
    It is recommended to study the the "Step-by-step user guide" (developer use 
    case) on this platform to learn how to run the script.
    The data package contains a sample dataset for Germany and the year 2016
version: "2017-07-03"
keywords: [Open Power System Data, MERRA-2, wind, solar, temperature, density, 
            pressure]
geographical-scope: Worldwide (German sample dataset for 2016)
description: Script for the download of MERRA-2 weather data
resources:
    - path: weather_data_GER_2016.csv
      format: csv
      encoding: UTF-8
      schema:         
        fields:
            - name: timestamp
              type: date-time
              format: YYYY-MM-DDTHH:MM:SSZ
              description: Start of timeperiod in Coordinated Universal Time
            - name: cumulated hours
              type: number
              format: integer
              description: summarized number of hours for the timeperiod of the dataset
            - name: lat
              type: geopoint
              format: lat
              description: Latitude coordinates
            - name: lon
              type: geopoint
              format: lon
              description: Longitude coordinates
            - name: v1
              type: number
              format: float
              description: wind speed 2 meters above displacement height
            - name: v2
              type: number
              format: float
              description: wind speed 10 meters above displacement height
            - name: v_50m
              type: number
              format: float
              description: wind speed 50 meters above ground
            - name: h1
              type: number
              format: float
              description: height above ground corresponding to v1
            - name: h2
              type: number
              format: integer
              description: height above ground corresponding to v2
            - name: z0
              type: number
              format: integer
              description: roughness length
            - name: SWTDN
              type: number
              format: float
              description: total top-of-the-atmosphere horizontal radiation
            - name: SWGDN
              type: number
              format: float
              description: total ground horizontal radiation
            - name: T
              type: number
              format: float
              description: Temperature 2 meters above displacement height
            - name: rho
              type: number
              format: float
              description: air density at surface
            - name: p
              type: number
              format: float
              description: air pressure at surface
            
licenses:
    - type: MIT license
      url: http://www.opensource.org/licenses/MIT
sources:
    - name: MERRA-2 
      web: https://gmao.gsfc.nasa.gov/reanalysis/MERRA-2/
      source: National Aeronautics and Space Administration - Goddard Space Flight Center
contributors:
    - name: Martin Jahn
      email: martin.jahn@uni-flensburg.de
    - name: Jan Urbansky

views: True
documentation: https://github.com/Open-Power-System-Data/weather_data/blob/2017-07-05/main.ipynb
last_changes: corrected typos, slight modifications (file names)
"""

metadata = yaml.load(metadata)

datapackage_json = json.dumps(metadata, indent=4, separators=(',', ': '))

with open('datapackage.json', 'w') as f:
    f.write(datapackage_json)

## Generating checksums

In [38]:
def get_sha_hash(path, blocksize=65536):
    sha_hasher = hashlib.sha256()
    with open(path, 'rb') as f:
        buffer = f.read(blocksize)
        while len(buffer) > 0:
            sha_hasher.update(buffer)
            buffer = f.read(blocksize)
        return sha_hasher.hexdigest()


output_path = ''

files = [
    'weather_data_GER_2016.csv',
    'weather_data_GER_2016.sqlite']

with open(os.path.join(output_path, 'checksums.txt'), 'w') as f:
    for file_name in files:
        file_hash = get_sha_hash(os.path.join(output_path, file_name))
        f.write('{},{}\n'.format(file_name, file_hash))